[theme]

# Primary accent color for interactive elements.
primaryColor = "#56a832"

# Background color for the main content area.
# backgroundColor = "#e1f5ef"

# Background color used for the sidebar and most interactive widgets.
# secondaryBackgroundColor = "#7cbfa2"

# Color used for almost all text.
textColor = "#093612"

# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
font = "sans serif"


[server]

runOnSave = true